### ISSUE TITLE
Can't create branch

### ISSUE THREAD

**Issue by mb121612** [githubteacher/feb-developers#109]

**Comment by patrickmckenna** [comment]
@mb121612 would you please posting a screenshot?

**Comment by patrickmckenna** [comment]
What browser are you using, @mb121612?

**Comment by mb121612** [comment]
I'm using an ancient version (what our company allows at this point). IE9

**Comment by mb121612** [comment]
I can try switching to crome.

**Comment by patrickmckenna** [comment]
@mb121612 Yeah, you'll need to change that. Please see https://github.com/githubteacher/feb-developers/issues/110#issuecomment-187823448
