### ISSUE TITLE
Can't create branch

### ISSUE THREAD

**Issue by rlappo** [githubteacher/feb-developers#110]
Branch drop-down doesn't work

**Comment by patrickmckenna** [comment]
@rlappo would you please post a screenshot of what what you see? Also, what browser are you using?

cf #109

**Comment by bsanders** [comment]
@rlappo , did you make a comment on issue #1?

**Comment by patrickmckenna** [comment]
Yeah, they're collaborators, @bsanders. But thanks for assisting!

![image](https://cloud.githubusercontent.com/assets/3589536/13261085/587db0ea-da13-11e5-80e3-13ec0b3df7f1.png)

**Comment by patrickmckenna** [comment]
@rlappo have you tried clicking the "selecting them" text?

![image](https://cloud.githubusercontent.com/assets/3589536/13261112/8390d578-da13-11e5-92d4-4e45b206cbb2.png)

**Comment by mb121612** [comment]
Yes. I tried selecting them option.

**Comment by rlappo** [comment]
I’m confused.  What is it you’re asking for at this point?

-Rich

**Comment by patrickmckenna** [comment]
@rlappo @mb121612 When I visit the "code" tab, I see this:

![image](https://cloud.githubusercontent.com/assets/3589536/13261242/0d76b492-da14-11e5-9130-c839f1e8df2f.png)

i.e. the drop-down menu does appear. Would you mind posting a screenshot of what you see?

**Comment by mb121612** [comment]
Sorry. Was told to check add to this issue. Can't get branches created.

**Comment by rlappo** [comment]
Here’s what I see.  But when I click on the Branch drop-down, it doesn’t display any options.

[cid:image001.png@01D16E21.280F6A10]

**Comment by patrickmckenna** [comment]
@rlappo unfortunately image attachments don't come through via email. Would you mind replying to this Issue in GitHub itself?

**Comment by rlappo** [comment]
What's the best way to get a screenshot in here?  Paste from clipboard doesn't seem to work.

**Comment by rlappo** [comment]
By the way, I'm using ancient IE9.

**Comment by patrickmckenna** [comment]
@rlappo please see https://github.com/githubteacher/feb-developers/issues/110#issuecomment-187817705

**Comment by patrickmckenna** [comment]
@rlappo ah, ok, can you use a different browser, e.g. Chrome?

**Comment by rlappo** [comment]
Not right away.  I’ll have to work on it later.  Guess I’ll just follow along for now.

**Comment by patrickmckenna** [comment]
FYI, @rlappo and @mb121612, if you're using IE, you need 11. Please see our [supported browsers page](https://help.github.com/articles/supported-browsers/).

**Comment by rlappo** [comment]
OK, firefox seems to work.  But way too far behind now ☺

**Comment by patrickmckenna** [comment]
Sorry, @rlappo! You will have the recording, though.
